#!/bin/bash

SERVER=$1

if [ -z "$SERVER" ]; then
  echo "FEIL: Oppgi ip addresse eller servernavn til pi'en du vil ssh'e til"
  exit 1
fi

shift

DESTINATION="pi@$SERVER"
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

source "$SCRIPT_DIR/options"

echo "Connecting to $DESTINATION..."
ssh $SSH_OPTIONS "$DESTINATION" "$@"
